# Generated by Django 5.0.6 on 2026-03-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cancha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Cancha 1, Cancha Central, Cancha Techada",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Información adicional (superficie, iluminación, etc.)",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcá si la cancha está fuera de servicio",
                        verbose_name="Activa",
                    ),
                ),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cancha",
                "verbose_name_plural": "Canchas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="HorarioDisponible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hora_inicio",
                    models.TimeField(
                        help_text="Ej: 08:00", verbose_name="Hora de inicio"
                    ),
                ),
                (
                    "hora_fin",
                    models.TimeField(help_text="Ej: 09:00", verbose_name="Hora de fin"),
                ),
                (
                    "dias_semana",
                    models.CharField(
                        help_text="Separados por coma. Ej: lunes,martes,miércoles",
                        max_length=100,
                        verbose_name="Días disponibles",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Horario disponible",
                "verbose_name_plural": "Horarios disponibles",
                "ordering": ["hora_inicio"],
            },
        ),
    ]
