# Generated by Django 5.0.6 on 2026-03-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="En pesos argentinos",
                        max_digits=10,
                        verbose_name="Monto",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("rechazado", "Rechazado"),
                            ("simulado", "Simulado (demo)"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado del pago",
                    ),
                ),
                (
                    "mp_preference_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="MP Preference ID"
                    ),
                ),
                (
                    "mp_payment_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="MP Payment ID"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pago",
                        to="reservas.reserva",
                        verbose_name="Reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-creado_en"],
            },
        ),
    ]
